#!/usr/bin/env bash

set -Eeuo pipefail

command -v gofmt >/dev/null || exit 1

while IFS= read -r -d '' file; do
  gofmt -w "$file"
  git add "$file"
done < <(
  git diff --cached \
    --name-only \
    --diff-filter=ACMR \
    -- '*.go' \
    -z
)