package syntax

func Text(kind SyntaxKind) string {
	switch kind {
	case KeywordDefer:
		return "defer"
	case KeywordDo:
		return "do"
	case KeywordElse:
		return "else"
	case KeywordEnd:
		return "end"
	case KeywordEnum:
		return "enum"
	case KeywordFn:
		return "fn"
	case KeywordFor:
		return "for"
	case KeywordIf:
		return "if"
	case KeywordImport:
		return "import"
	case KeywordImportC:
		return "importc"
	case KeywordIs:
		return "is"
	case KeywordLoop:
		return "loop"
	case KeywordMut:
		return "mut"
	case KeywordReturn:
		return "return"
	case KeywordStop:
		return "stop"
	case KeywordStruct:
		return "struct"
	case KeywordThen:
		return "then"
	case KeywordType:
		return "type"
	case KeywordVar:
		return "var"
	case KeywordWhile:
		return "while"
	case PlusToken:
		return "+"
	case PlusEqualsToken:
		return "+="
	case MinusToken:
		return "-"
	case MinusEqualsToken:
		return "-="
	case StarToken:
		return "*"
	case StarEqualsToken:
		return "*="
	case SlashToken:
		return "/"
	case SlashEqualsToken:
		return "/="
	case EqualsToken:
		return "="
	case EqualsEqualsToken:
		return "=="
	case LessToken:
		return "<"
	case LessEqualsToken:
		return "<="
	case GreaterToken:
		return ">"
	case GreaterEqualsToken:
		return ">="
	case AmpersandToken:
		return "&"
	case AmpersandAmpersandToken:
		return "&&"
	case PipeToken:
		return "|"
	case PipePipeToken:
		return "||"
	case CaretToken:
		return "^"
	case OpenParenToken:
		return "("
	case CloseParenToken:
		return ")"
	case OpenBracketToken:
		return "["
	case CloseBracketToken:
		return "]"
	case OpenBraceToken:
		return "{"
	case CloseBraceToken:
		return "}"
	case CommaToken:
		return ","
	case ColonToken:
		return ":"
	case SemicolonToken:
		return ";"
	case DotToken:
		return "."
	case NewlineToken:
		return "\n"
	default:
		return ""
	}
}
