// Code generated by "stringer -type=Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Identifier-1]
	_ = x[IntegerLiteral-2]
	_ = x[StringLiteral-3]
	_ = x[FloatLiteral-4]
	_ = x[CharacterLiteral-5]
	_ = x[KwFn-6]
	_ = x[KwDo-7]
	_ = x[KwVar-8]
	_ = x[KwMut-9]
	_ = x[KwReturn-10]
	_ = x[KwEnd-11]
	_ = x[KwChar-12]
	_ = x[KwInt-13]
	_ = x[KwBool-14]
	_ = x[KwNull-15]
	_ = x[KwUnit-16]
	_ = x[KwString-17]
	_ = x[KwFloat-18]
	_ = x[KwIf-19]
	_ = x[KwThen-20]
	_ = x[KwElse-21]
	_ = x[KwStruct-22]
	_ = x[KwIs-23]
	_ = x[KwImportC-24]
	_ = x[KwImport-25]
	_ = x[KwWhile-26]
	_ = x[KwLoop-27]
	_ = x[KwStop-28]
	_ = x[KwDefer-29]
	_ = x[KwEnum-30]
	_ = x[Plus-31]
	_ = x[Minus-32]
	_ = x[Star-33]
	_ = x[Slash-34]
	_ = x[Equal-35]
	_ = x[EqualEqual-36]
	_ = x[Bang-37]
	_ = x[BangEqual-38]
	_ = x[Less-39]
	_ = x[LessEqual-40]
	_ = x[Greater-41]
	_ = x[GreaterEqual-42]
	_ = x[Arrow-43]
	_ = x[Modulo-44]
	_ = x[Pipe-45]
	_ = x[LogicalOr-46]
	_ = x[LogicalAnd-47]
	_ = x[Ampersand-48]
	_ = x[Caret-49]
	_ = x[Tilde-50]
	_ = x[PlusEqual-51]
	_ = x[MinusEqual-52]
	_ = x[StarEqual-53]
	_ = x[SlashEqual-54]
	_ = x[ModuloEqual-55]
	_ = x[CaretEqual-56]
	_ = x[PipeEqual-57]
	_ = x[AmpersandEqual-58]
	_ = x[PlusPlus-59]
	_ = x[MinusMinus-60]
	_ = x[LessLess-61]
	_ = x[GreaterGreater-62]
	_ = x[LeftParen-63]
	_ = x[RightParen-64]
	_ = x[LeftBrace-65]
	_ = x[RightBrace-66]
	_ = x[Comma-67]
	_ = x[Semicolon-68]
	_ = x[Colon-69]
	_ = x[Dot-70]
	_ = x[LeftBracket-71]
	_ = x[RightBracket-72]
	_ = x[Newline-73]
	_ = x[EOF-74]
	_ = x[Error-75]
}

const _Kind_name = "unknownidentifierinteger_literalstring_literalfloat_literalcharacter_literalkw_fnkw_dokw_varkw_mutkw_returnkw_endkw_charkw_intkw_boolkw_nullkw_unitkw_stringkw_floatkw_ifkw_thenkw_elsekw_structkw_iskw_importckw_importkw_whilekw_loopkw_stopkw_deferkw_enumplusminusstarslashequalequal_equalbangbang_equallessless_equalgreatergreater_equalarrowmodulopipelogical_orlogical_andampersandcarettildeplus_equalminus_equalstar_equalslash_equalmodulo_equalcaret_equalpipe_equalampersand_equalplus_plusminus_minusless_lessgreater_greaterleft_parenright_parenleft_braceright_bracecommasemicoloncolondotleft_bracketright_bracketnewlineeoferror"

var _Kind_index = [...]uint16{0, 7, 17, 32, 46, 59, 76, 81, 86, 92, 98, 107, 113, 120, 126, 133, 140, 147, 156, 164, 169, 176, 183, 192, 197, 207, 216, 224, 231, 238, 246, 253, 257, 262, 266, 271, 276, 287, 291, 301, 305, 315, 322, 335, 340, 346, 350, 360, 371, 380, 385, 390, 400, 411, 421, 432, 444, 455, 465, 480, 489, 500, 509, 524, 534, 545, 555, 566, 571, 580, 585, 588, 600, 613, 620, 623, 628}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
