// Code generated by "stringer -type=Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Identifier-1]
	_ = x[IntegerLiteral-2]
	_ = x[StringLiteral-3]
	_ = x[FloatLiteral-4]
	_ = x[CharacterLiteral-5]
	_ = x[KwFn-6]
	_ = x[KwDo-7]
	_ = x[KwVar-8]
	_ = x[KwMut-9]
	_ = x[KwReturn-10]
	_ = x[KwEnd-11]
	_ = x[KwChar-12]
	_ = x[KwInt-13]
	_ = x[KwUnit-14]
	_ = x[KwString-15]
	_ = x[KwFloat-16]
	_ = x[KwIf-17]
	_ = x[KwThen-18]
	_ = x[KwElse-19]
	_ = x[KwStruct-20]
	_ = x[KwIs-21]
	_ = x[KwImportC-22]
	_ = x[KwEnum-23]
	_ = x[Plus-24]
	_ = x[Minus-25]
	_ = x[Star-26]
	_ = x[Slash-27]
	_ = x[Equal-28]
	_ = x[EqualEqual-29]
	_ = x[Bang-30]
	_ = x[BangEqual-31]
	_ = x[Less-32]
	_ = x[LessEqual-33]
	_ = x[Greater-34]
	_ = x[GreaterEqual-35]
	_ = x[Arrow-36]
	_ = x[Modulo-37]
	_ = x[Pipe-38]
	_ = x[LogicalOr-39]
	_ = x[LogicalAnd-40]
	_ = x[Ampersand-41]
	_ = x[Caret-42]
	_ = x[Tilde-43]
	_ = x[PlusEqual-44]
	_ = x[MinusEqual-45]
	_ = x[StarEqual-46]
	_ = x[SlashEqual-47]
	_ = x[ModuloEqual-48]
	_ = x[CaretEqual-49]
	_ = x[PipeEqual-50]
	_ = x[AmpersandEqual-51]
	_ = x[PlusPlus-52]
	_ = x[MinusMinus-53]
	_ = x[LessLess-54]
	_ = x[GreaterGreater-55]
	_ = x[LeftParen-56]
	_ = x[RightParen-57]
	_ = x[LeftBrace-58]
	_ = x[RightBrace-59]
	_ = x[Comma-60]
	_ = x[Semicolon-61]
	_ = x[Colon-62]
	_ = x[Dot-63]
	_ = x[LeftBracket-64]
	_ = x[RightBracket-65]
	_ = x[Newline-66]
	_ = x[EOF-67]
	_ = x[Error-68]
}

const _Kind_name = "unknownidentifierinteger_literalstring_literalfloat_literalcharacter_literalkw_fnkw_dokw_varkw_mutkw_returnkw_endkw_charkw_intkw_unitkw_stringkw_floatkw_ifkw_thenkw_elsekw_structkw_iskw_importkw_enumplusminusstarslashequalequal_equalbangbang_equallessless_equalgreatergreater_equalarrowmodulopipelogical_orlogical_andampersandcarettildeplus_equalminus_equalstar_equalslash_equalmodulo_equalcaret_equalpipe_equalampersand_equalplus_plusminus_minusless_lessgreater_greaterleft_parenright_parenleft_braceright_bracecommasemicoloncolondotleft_bracketright_bracketnewlineeoferror"

var _Kind_index = [...]uint16{0, 7, 17, 32, 46, 59, 76, 81, 86, 92, 98, 107, 113, 120, 126, 133, 142, 150, 155, 162, 169, 178, 183, 192, 199, 203, 208, 212, 217, 222, 233, 237, 247, 251, 261, 268, 281, 286, 292, 296, 306, 317, 326, 331, 336, 346, 357, 367, 378, 390, 401, 411, 426, 435, 446, 455, 470, 480, 491, 501, 512, 517, 526, 531, 534, 546, 559, 566, 569, 574}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
