name: Pull Request Discord Notification

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  notify:
    name: Send webhook
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: "Pull Request ${{ github.event.action }}: #${{ github.event.pull_request.number }}"
          embed-description: |
            **${{ github.event.pull_request.title }}**

            Branch: `${{ github.event.pull_request.head.ref }}` into `${{ github.event.pull_request.base.ref }}`
          embed-url: ${{ github.event.pull_request.html_url }}
          # Dynamically set color: green for opened/reopened, blue for updates (synchronize)
          embed-color: ${{ github.event.action == 'synchronize' && '3447003' || '5814783' }}
          embed-author-name: ${{ github.event.pull_request.user.login }}
          embed-author-url: ${{ github.event.pull_request.user.html_url }}
          embed-author-icon-url: ${{ github.event.pull_request.user.avatar_url }}
          embed-footer-text: ${{ github.repository }}